export default [
  {
    id: 1,
    img: "https://source.unsplash.com/WLxQvbMyfas",
    href:"https://goo.gl/maps/Wn1LQpPh6E1sFNVu5",
    location: "JAPAN",
    name: "Mount Fuji",
    date: "12 Jan, 2023 - 24 Jan, 2023",
    info: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
  },
  {
    id: 2,
    img: "https://source.unsplash.com/JmuyB_LibRo",
    href:"https://goo.gl/maps/qeWsL7CzgLFkEhFb9",
    location: "AUSTRALIA",
    name: "Sydney Opera House",
    date: "27 May, 2023 - 8 Jun, 2023",
    info: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings",
  },
  {
    id: 3,
    img: "https://source.unsplash.com/3PeSjpLVtLg",
    href:"https://goo.gl/maps/McYJvgyMTZHkZKie8",
    location: "NORWAY",
    name: "Geirangerfjord",
    date: "01 Oct, 2023 - 18 Nov, 2023",
    info: "The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
  },
  {
    id: 4,
    img: "https://images.unsplash.com/photo-1549466785-f5c1771646cc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1548&q=80",
    href:"https://goo.gl/maps/R81TZUfNrymg4i1Z9",
    location: "GEORGIA",
    name: "Gudauri",
    date: "10 Mar, 2023 - 27 Apr, 2023",
    info: "The monument was built in 1983 to commemorate the 200-year anniversary of the Treaty of Georgievsk and celebrate diplomatic relations between Georgia and its neighbour to the north. It was designed by Georgian architect George Chakhava.",
  },
  {
    id: 5,
    img: "https://wander-lush.org/wp-content/uploads/2022/04/Emily-Lush-things-to-do-in-Batumi-Georgia-new-Octopus.jpg",
    href:"https://goo.gl/maps/UB7mqEHuCzDGAuLG9",
    location: "GEORGIA",
    name: "Batumi",
    date: "25 May, 2023 - 11 Jul, 2023",
    info: "Batumi Octopus: Built in 1975 by architect: George Chakhava and mosaic artist Zurab Kapanadze, this massive three-dimensional Soviet-style mosaic sculpture has a cafe inside (formerly known as Cafe Fantasia). Locals call it ‘Octopus’ for obvious reasons. It was recently restored.",
  },
  {
    id: 6,
    img: "https://www.explore.com/img/gallery/the-75-most-popular-american-tourist-destinations/mount-rushmore-1667582510.webp",
    href:"https://goo.gl/maps/3NirSVsdAcKPS7nu5",
    location: "USA",
    name: "Mount Rushmore",
    date: "03 Aug, 2023 - 20 Sep, 2023",
    info: "Mount Rushmore features sculptures of four former presidents carved into the Black Hills near Keystone, South Dakota. Every year, more than two million visitors come to view George Washington, Thomas Jefferson, Theodore Roosevelt and Abraham Lincoln, whose stone heads measure 60 feet each.",
  },
  {
    id: 7,
    img: "https://www.planetware.com/photos-large/I/italy-colosseum-day.jpg",
    href:"https://goo.gl/maps/ZB5JyvTkngqwy1XE7",
    location: "ITALY",
    name: "Colosseum",
    date: "14 Nov, 2023 - 01 Jan, 2023",
    info: "This huge amphitheater, the largest of its kind ever built by the Roman Empire and the largest of their constructions to survive, remained a model for sports facilities right up to modern times. Built by Vespasian in 72 CE and enlarged by the addition of a fourth story by his son, Titus, it was a venue for public spectacles and shows - even mock sea battles.",
  },
  {
    id: 8,
    img: "https://www.planetware.com/photos-large/EGY/egypt-cairo-pyramids-of-giza.jpg",
    href:"https://goo.gl/maps/gwHiUgDp7cK5fak56",
    location: "EGYPT",
    name: "Pyramids of Giza",
    date: "23 Jan, 2023 - 11 Mar, 2023",
    info: "The last surviving wonder of the Seven Wonders of the Ancient World, the Pyramids of Giza are one of the world's most recognizable landmarks.",
  },
  {
    id: 9,
    img: "https://www.planetware.com/wpimages/2020/08/top-attractions-in-the-world-peru-machu-picchu-overview.jpg",
    href:"https://goo.gl/maps/i2krrN9zvQ9mCxw5A",
    location: "PERU",
    name: "Machu Picchu",
    date: "04 Apr, 2023 - 21 May, 2023",
    info: "If you are planning to see only one attraction in South America, this is the place to come. The ancient Inca city of Machu Picchu is arguably the most impressive ruined city in the world.",
  },
];
